'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {FileText,Link2,Rss,Download,LockKeyhole,Search,AlertCircle,Upload,Loader2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import DOMPurify from 'dompurify';
import {clipHtml,parseFeed,safeUrl,textDois,doiFrom} from '@/lib/clip';
import type {Extracted,DocumentRow} from '@/lib/types';

async function json<T>(response:Response):Promise<T>{if(!response.ok){const text=await response.text();let message=text;try{message=JSON.parse(text).error||text;}catch{}throw new Error(message||`Request failed (${response.status})`);}return response.json() as Promise<T>;}
function download(name:string,value:string,type='application/json'){const url=URL.createObjectURL(new Blob([value],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
function label(status:string){return ({partial:'Needs review',ready:'Extracted',uploaded:'Original saved',failed:'Extraction failed'} as Record<string,string>)[status]||status;}

export default function Workspace(){
 const [documents,setDocuments]=useState<DocumentRow[]>([]),[selected,setSelected]=useState<DocumentRow|null>(null),[result,setResult]=useState<Extracted|null>(null);
 const [url,setUrl]=useState(''),[kind,setKind]=useState('file'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[progress,setProgress]=useState(0),[query,setQuery]=useState('');
 const [saveState,setSaveState]=useState(''),[cancellable,setCancellable]=useState(false),[view,setView]=useState('text');const cancel=useRef<(()=>void)|null>(null),busyRef=useRef(false),viewGeneration=useRef(0),captureRef=useRef<(url:string,feed:boolean)=>Promise<unknown>>(async()=>{});
 const refresh=useCallback(async(search='')=>{const data=await json<{documents:DocumentRow[]}>(await fetch(`/api/documents?q=${encodeURIComponent(search)}`));setDocuments(data.documents);},[]);
 useEffect(()=>{void refresh().catch(e=>setError(e.message));},[refresh]);
 async function openRecord(record:DocumentRow){if(busyRef.current)return;const generation=++viewGeneration.current;setError('');try{const data=await json<{record:DocumentRow,result:Extracted|null}>(await fetch(`/api/documents/${record.id}`));if(generation!==viewGeneration.current||busyRef.current)return;setSelected(data.record);setResult(data.result);setSaveState('Saved privately');setView('text');}catch(e){setError(String(e));}}
 async function persist(record:DocumentRow,extracted:Extracted){extracted.links=extracted.links.map(link=>({...link,doi:link.doi||doiFrom(link.url)}));setResult(extracted);setSaveState('Saving…');await json(await fetch(`/api/documents/${record.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(extracted)}));setSelected({...record,title:extracted.title,status:extracted.status,engine:extracted.engine});setSaveState('Saved privately');await refresh(query);}
 async function pdf(bytes:ArrayBuffer,name:string):Promise<Extracted>{return new Promise((resolve,reject)=>{
  setCancellable(true);const worker=new Worker('/pdf-worker.js',{type:'module'});const timer=setTimeout(()=>{worker.terminate();reject(new Error('Extraction reached the 60-second browser limit. The original remains saved.'));},60000);
  const stop=()=>{clearTimeout(timer);worker.terminate();cancel.current=null;setCancellable(false);};cancel.current=()=>{stop();reject(new Error('Extraction cancelled. The original remains saved.'));};
  worker.onmessage=e=>{if(e.data.progress){setProgress(100*e.data.progress/e.data.total);setMessage(`Extracting page ${e.data.progress} of ${e.data.total}`);}else if(e.data.error){stop();reject(new Error(e.data.error));}else if(e.data.result){stop();const value=e.data.result as Extracted;value.links.push(...textDois(value.text));resolve(value);}};
  worker.onerror=e=>{stop();reject(new Error(e.message||'The PDF worker stopped unexpectedly.'));};worker.postMessage({bytes,name},[bytes]);
 });}
 async function processFile(file:File,sourceUrl='',decodedSource?:string){
  if(file.size>8*1024*1024)throw new Error('This alpha accepts files up to 8 MiB. The native CLI handles larger files.');
  const fileKind=/\.pdf$/i.test(file.name)||file.type==='application/pdf'?'pdf':/\.(xml|rss|atom)$/i.test(file.name)?'feed':/\.jsonl?$/i.test(file.name)?'json':'html';
  setMessage('Saving the original…');const record=await json(await fetch(`/api/documents?${new URLSearchParams({name:file.name,kind:fileKind,...(sourceUrl?{url:sourceUrl}:{})})}`,{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:file})) as DocumentRow;setSelected(record);setResult(null);setView('text');let extracted:Extracted;
  try{
   if(fileKind==='pdf'){setMessage('Starting the PDF worker…');extracted=await pdf(await file.arrayBuffer(),file.name);}
   else if(fileKind==='feed')extracted=parseFeed(decodedSource??await file.text(),sourceUrl||'https://saved.invalid/');
   else if(fileKind==='json'){
    const text=await file.text();let raw;try{raw=JSON.parse(text);}catch{raw=text.split(/\r?\n/).filter(Boolean).map(line=>JSON.parse(line));}const entries=Array.isArray(raw)?raw:[raw];if(entries.length!==1)throw new Error('Import one native extraction record at a time.');const entry=entries[0];if(!entry||!Array.isArray(entry.pages))throw new Error('Expected a native TPE JSON extraction record with pages.');
    extracted={title:entry.metadata?.title||file.name,text:entry.pages.map((p:{text?:string})=>p.text||'').join('\n\n'),pages:entry.pages,links:entry.pages.flatMap((p:{page?:number,links?:{uri:string,bbox?:unknown}[]})=>(p.links||[]).map(l=>({url:l.uri,rect:l.bbox,page:p.page,kind:'imported PDF link'}))),warnings:[...(entry.warnings||[]),'Imported native result: its engine and status are not independently verified by this Site.'],metadata:{nativeRecord:entry},engine:`Imported: ${entry.backend?.name||'TPE'} ${entry.backend?.version||''}`,status:'partial'};
   }else extracted=clipHtml(decodedSource??await file.text(),sourceUrl||'https://saved.invalid/',file.name);
  }catch(e){const failed:Extracted={title:file.name,text:'',links:[],warnings:[e instanceof Error?e.message:String(e)],engine:fileKind==='pdf'?'pdf-oxide-wasm 0.3.77':'capture',status:'failed'};try{await persist(record,failed);}catch{setSaveState('Original saved; result could not be saved.');}throw e;}
  try{await persist(record,extracted);}catch(e){setSaveState('Result not saved — export it or retry below.');throw e;}
  setMessage('Extraction saved.');return {id:record.id,title:extracted.title,status:extracted.status,links:extracted.links.length};
 }
 async function operation(action:()=>Promise<unknown>){if(busyRef.current)throw new Error('An import is already running.');busyRef.current=true;viewGeneration.current++;setBusy(true);setError('');setProgress(0);try{return await action();}catch(e){setError(e instanceof Error?e.message:String(e));throw e;}finally{busyRef.current=false;setBusy(false);cancel.current=null;setCancellable(false);}}
 async function capture(source:string,feed:boolean){return operation(async()=>{setMessage('Fetching the source…');const data=await json<{html:string,originalBase64:string,url:string,contentType:string}>(await fetch('/api/capture',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:source})}));const isFeed=feed||/rss|atom/i.test(data.contentType)||/<(?:\w+:)?(?:rss|feed|RDF)(?:\s|>)/.test(data.html.slice(0,2000));const bytes=Uint8Array.from(atob(data.originalBase64),c=>c.charCodeAt(0));return processFile(new File([bytes],`${new URL(data.url).hostname}.${isFeed?'xml':'html'}`,{type:isFeed?'application/xml':'text/html'}),data.url,data.html);});}captureRef.current=capture;
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'capture_source',title:'Capture a web page or feed',description:'Fetch and privately save a public web page or feed, extract its content and links, and display the result.',inputSchema:{type:'object',properties:{url:{type:'string'},feed:{type:'boolean'}},required:['url'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||!('url' in input)||typeof input.url!=='string'||!safeUrl(input.url))throw new Error('A public HTTP or HTTPS URL is required.');return captureRef.current(input.url,'feed'in input&&input.feed===true);}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[]);
 const dois=result?.links.filter(l=>l.doi)||[];
 return <main>
  <header className="flex flex-wrap items-center justify-between gap-4 border-b border-border pb-5"><div className="flex items-center gap-3"><FileText size={30}/><h1 className="text-2xl font-semibold">TPE</h1><span className="text-base text-muted-foreground">Private alpha</span></div><span className="flex items-center gap-2 text-base text-muted-foreground"><LockKeyhole size={18}/>Only you</span></header>
  <div className="workspace-grid"><section className="intake"><h2 className="mb-5 text-2xl font-semibold">Import and extract</h2>
   <Tabs value={kind} onValueChange={setKind}><TabsList className="w-full h-auto"><TabsTrigger value="file" className="text-base"><Upload/>File</TabsTrigger><TabsTrigger value="web" className="text-base"><Link2/>Web</TabsTrigger><TabsTrigger value="feed" className="text-base"><Rss/>Feed</TabsTrigger></TabsList>
    <TabsContent value="file"><div className="intake-box"><label htmlFor="file" className="block font-semibold mb-3">PDF, saved HTML, feed XML, or TPE JSON</label><input id="file" type="file" accept=".pdf,.html,.htm,.xml,.rss,.atom,.json,.jsonl" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void operation(()=>processFile(file)).catch(()=>{});e.target.value='';}}/><p className="help mt-3">Up to 8 MiB. Browser PDFs: up to 150 pages.</p></div></TabsContent>
    {['web','feed'].map(tab=><TabsContent key={tab} value={tab}><form className="intake-box" onSubmit={e=>{e.preventDefault();void capture(url,tab==='feed').catch(()=>{});}}><label htmlFor={`url-${tab}`} className="block font-semibold mb-3">{tab==='feed'?'RSS or Atom URL':'Page URL'}</label><input id={`url-${tab}`} type="url" required placeholder="https://" value={url} onChange={e=>setUrl(e.target.value)} disabled={busy}/><Button type="submit" className="w-full mt-4 text-base" disabled={busy||!url.trim()}>{busy?<Loader2 className="animate-spin"/>:tab==='feed'?<Rss/>:<Link2/>}{tab==='feed'?'Read feed':'Capture page'}</Button><p className="help mt-3">{tab==='feed'?'Entry content and enclosure links are retained. Refresh is manual.':'Public HTML is captured without running page scripts. For interactive pages, import a saved HTML snapshot.'}</p></form></TabsContent>)}
   </Tabs>
   {busy&&<div className="mt-4" role="status"><p>{message}</p><Progress value={progress} className="mt-3"/>{cancellable&&<Button variant="outline" className="mt-3" onClick={()=>cancel.current?.()}>Cancel extraction</Button>}</div>}
   {error&&<div className="notice error" role="alert"><AlertCircle size={20}/><p>{error}</p></div>}
   <div className="mt-8 border-t border-border pt-6"><h2 className="text-xl font-semibold">Saved documents</h2><form className="mt-3 flex gap-2" onSubmit={e=>{e.preventDefault();void refresh(query).catch(e=>setError(e.message));}}><label className="sr-only" htmlFor="search">Search saved text</label><input id="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search title or text"/><Button type="submit" variant="outline" aria-label="Search"><Search/></Button></form><div className="mt-3 document-list">{documents.length?documents.map(record=><button key={record.id} disabled={busy} aria-current={selected?.id===record.id?true:undefined} className={`document-item ${selected?.id===record.id?'selected':''}`} onClick={()=>void openRecord(record)}><span className="font-semibold block break-words">{record.title}</span><span className="help block mt-1">{record.kind.toUpperCase()} · {label(record.status)}</span></button>):<p className="help py-5">Your saved sources will appear here.</p>}</div></div>
  </section><section className="result-pane" aria-label="Extraction result">
   {!selected?<div className="empty-state"><FileText size={40}/><h2 className="text-2xl font-semibold mt-5">Your source, made readable</h2><p className="text-muted-foreground mt-3">Import a document or capture a page. Text, embedded URLs, DOI evidence, tables, and source metadata stay together.</p><div className="mt-8 border-t border-border pt-5 text-left"><p className="font-semibold">Originals are retained</p><p className="help mt-2">Extraction is a separate result. Uncertain output is labelled for review, and every result can be exported.</p></div></div>:<>
    <div className="flex flex-wrap gap-3 items-start justify-between"><div className="min-w-0"><p className="help mb-2" role="status" aria-live="polite">{label(selected.status)} · {saveState}</p><h2 className="text-2xl font-semibold break-words">{result?.title||selected.title}</h2></div><Button asChild variant="outline"><a href={`/api/documents/${selected.id}/original`}><Download/>Original</a></Button></div>
    {result?<><div className="flex flex-wrap gap-3 mt-4"><span className="metric">{result.pages?.length??result.entries?.length??'—'} {result.entries?'entries':'pages'}</span><span className="metric">{result.links.length} links</span><span className="metric">{dois.length} DOI links</span></div>
    <Tabs value={view} onValueChange={setView} className="mt-6"><TabsList className="w-full h-auto flex-wrap justify-start"><TabsTrigger value="text" className="text-base">Read</TabsTrigger><TabsTrigger value="links" className="text-base">Links & DOI</TabsTrigger><TabsTrigger value="evidence" className="text-base">Evidence</TabsTrigger></TabsList>
     <TabsContent value="text"><div className="flex gap-2 my-4 flex-wrap">{saveState.startsWith('Result not saved')&&<Button disabled={busy} onClick={()=>void operation(()=>persist(selected,result)).catch(()=>setSaveState('Result not saved — export it or retry below.'))}>Retry save</Button>}<Button variant="outline" onClick={()=>download('extraction.md',result.markdown||result.text,'text/markdown')}><Download/>Markdown</Button><Button variant="outline" onClick={()=>download('extraction.json',JSON.stringify({source:selected,...result},null,2))}><Download/>JSON</Button></div>{result.status==='failed'?<div className="notice error"><AlertCircle/><p>{result.warnings.join(' ')}</p></div>:result.html?<article className="reading" dangerouslySetInnerHTML={{__html:DOMPurify.sanitize(result.html,{FORBID_TAGS:['img','iframe','script','object','embed','form','svg','audio','video','source','track','picture','link'],FORBID_ATTR:['style','srcset']})}}/>:<article className="reading whitespace-pre-wrap">{result.markdown||result.text||'No text was extracted. Check the original and evidence.'}</article>}</TabsContent>
     <TabsContent value="links"><p className="help my-4">Embedded targets and printed DOI candidates are kept separately. Candidates have not been verified against a registry.</p><div className="space-y-4">{result.links.length?result.links.map((link,index)=><div key={index} className="link-card"><p className="help">{link.kind}{link.page?` · page ${link.page}`:''}{link.doi?' · DOI candidate':''}</p>{link.label&&<p className="mt-1">{link.label}</p>}{safeUrl(link.url)?<a href={link.url} target="_blank" rel="noreferrer noopener" className="break-all underline">{link.url}</a>:<code className="break-all">{link.url}</code>}</div>):<p>No links were found.</p>}</div></TabsContent>
     <TabsContent value="evidence"><dl className="evidence mt-5"><dt>Engine</dt><dd>{result.engine}</dd><dt>Original SHA-256</dt><dd className="break-all font-mono text-base">{selected.sha256}</dd><dt>Captured</dt><dd>{new Date(selected.created_at).toLocaleString()}</dd>{selected.source_url&&<><dt>Source</dt><dd className="break-all">{selected.source_url}</dd></>}</dl><h3 className="text-xl font-semibold mt-6">Review notes</h3><ul className="list-disc pl-6 mt-3 space-y-3">{result.warnings.map((warning,i)=><li key={i}>{warning}</li>)}</ul><details className="mt-6"><summary className="cursor-pointer font-semibold py-3">Metadata and structured data</summary><pre className="code-panel">{JSON.stringify(result.metadata||{},null,2)}</pre></details>{!!result.tables?.length&&<details className="mt-4"><summary className="cursor-pointer py-3">Captured tables ({result.tables.length})</summary><pre className="code-panel">{JSON.stringify(result.tables,null,2)}</pre></details>}</TabsContent>
    </Tabs></>:<div className="notice mt-6"><p>The original is saved. Extraction has not finished.</p></div>}
   </>}
  </section></div>
  <footer className="border-t border-border mt-8 pt-5 help"><details><summary className="cursor-pointer py-3">Alpha scope and design references</summary><p className="mt-3">The Site uses PDF Oxide’s Rust/WASM extraction in a disposable browser worker. Native PDFium, MuPDF, Poppler, CFF recovery and LiteParse components are being integrated and tested in the Rust engine; they are not hosted Site backends. Native TPE JSON results can be imported above.</p><p className="mt-3">HTML capture retains original content, links, metadata and table data. It does not execute source JavaScript or reproduce interactive charts. Feed refresh is manual.</p><p className="mt-3 flex flex-wrap gap-4"><a href="https://docs.paperless-ngx.com/" target="_blank" rel="noreferrer">Paperless-ngx</a><a href="https://bear.app/faq/browser-extensions/" target="_blank" rel="noreferrer">Bear Web Clipper</a><a href="https://github.com/mozilla/readability" target="_blank" rel="noreferrer">Mozilla Readability</a><a href="https://www.rssboard.org/rss-specification" target="_blank" rel="noreferrer">RSS</a><a href="https://www.rfc-editor.org/rfc/rfc4287" target="_blank" rel="noreferrer">Atom</a></p></details></footer>
 </main>;
}
